### PR TITLE
Merge upstream master.

### PR DESCRIPTION
**Pull request by ZeissS**
This merges the upstream master. We have two changes in oru branches

* Make Viper public - this also happened upstream
* Add RawUnmarshal() - I left this in.

Conflicts where only in viper.go

### CODE REVIEW

**Comment by ZeissS** [comment]
ping @zyndiecate I would like to have this, as I need the `GetDuration` function

**Comment by zyndiecate** [comment]
We forked this initially to be able to access the exported `Viper` type [0]. I see the upstream has this fixed. What about going back to the original repo? 

- [0] https://github.com/giantswarm/viper/pull/1

**Comment by ZeissS** [comment]
What about #2?

**Comment by ZeissS** [comment]
Btw, I see there is a `ReadConfig` function which more or less does the same - isn't that sufficient?

**Comment by zyndiecate** [comment]
Should work out. I would go for a try.

**Comment by ZeissS** [comment]
Closing then.

**Pull request closed without merging**
