### PR TITLE
read raw configuration by given bytes

### PR DESCRIPTION
**Pull request by zyndiecate**
This provides a method to load configuration without the need of filesystem actions.

### CODE REVIEW

**Comment by ZeissS** [comment]
I would prefer having a function that takes a `io.Reader`. The user can use `bytes.NewReader()` by itself.

**Comment by zyndiecate** [comment]
Agreed, but this is mostly just copy/paste. I would like to keep structure/architecture/interfaces as they are. It would be cool to be able to merge this back to the upstream in case the origin developer wants that. In that case I don't want to change too much and change things you suggested together with him.

**Comment by ZeissS** [comment]
ok

**Comment by ZeissS** [comment]
LGTM

**Pull request merged**
